### ISSUE TITLE
Adding the function litex-solve-all-steps-align

### ISSUE THREAD

**Issue by Doxdrum** [Atreyagaurav/litex-mode#6]
This patch adds the feature of solving the `sexp` step-by-step using the LaTeX `align` environment.

----
**Updated:** Attaching the right patch file.

[solve-align.tar.gz](https://github.com/Atreyagaurav/litex-mode/files/8090909/solve-align.tar.gz)

**Comment by Atreyagaurav** [comment]
Also a note:

Have you tried modifying the following variables to make them use the align environment to solve step by step? It should be better than adding a function that does the same thing but with different variables in my opinion.

| variable | default|
| litex-math-eqnarray-start|  “\begin{eqnarray*}\n” |
| litex-math-eqnarray-end | “\n\end{eqnarray*}\n” |
| litex-math-steps-eqnarray-join-string | ” &=& ” | 
| litex-math-steps-eqnarray-end-string | “\\\n” |

**Comment by Doxdrum** [comment]
> Hi, this file has empty patch file inside, can you make an pull request? That'll be easier for me.
> 
> Also, is there a reason you'll need solve with align environment instead of eqnarray environment? Those might do similar thing in my opinion.

Hi!

Firstly, thank you for your contribution... I see a lot of potential from it!

Sorry for the empty patch.... It was actually the first time I create a patch. I've updated the file, now it contains the *real* deal.

There is a slight difference in formatting when one uses `align` instead of `eqnarray`. There are lots of posts on the LaTeX forums about stopping using `eqnarray`... That's the reason I think should be useful to include the option (without dropping support of the `eqnarray` environment). Even thou there are more useful LaTeX packages (like `breqn`) for managing multiline expressions, the advantage of `align` is that it is included in the `amsmath` package, which is loaded by default when exporting from `org` to `LaTeX`
